spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate:
          ddl-auto: none

    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true